version: 2

models:

  - name: customer_metrics
    description: Customer-level KPIs and metrics.

    columns:
      - name: customer_state
        description: State of the customer.

      - name: total_customers
        description: Number of customers.

      - name: total_orders
        description: Number of orders.

  - name: fct_daily_revenue
    description: Daily revenue fact table.

    columns:
      - name: order_date
        description: Date of the order.
        tests:
          - unique
          - not_null

      - name: total_revenue
        description: Revenue generated on a particular day.

      - name: total_orders
        description: Number of orders on that day.

  - name: product_performance
    description: Product-level performance metrics.

    columns:
      - name: product_category_name
        description: Product category.

      - name: total_sales
        description: Number of sales.

      - name: revenue
        description: Revenue generated.

  - name: seller_scorecard
    description: Seller-level performance metrics.

    columns:
      - name: seller_state
        description: Seller state.

      - name: total_sellers
        description: Number of sellers.

      - name: seller_revenue
        description: Revenue generated by sellers.